# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bd2595b7e52d2317087d659ae0c58ccefa1811580269e6b896fdf09638a07d44fc28708d6847e8210d8e48660f50c1478db27641bf6500b76755a7f769a75af

test:
  secret_key_base: 2f79ad19104491fdfbbc0c399e09515a3823fac95e73c74dbd2ce61b927354ec29648b9bcc225e7db8064ea73d2c39369258c82136bf13c65639aa28fe4ee535

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
